### ISSUE TITLE
(Bug) Token's balance displayed incorrectly if it's less than 1

### ISSUE THREAD

**Issue by dennis00010011b** [poanetwork/nifty-wallet#194]
If you are reporting a problem with Nifty Wallet, please include the following information:

### What browser and version did you use?
*Chrome*
### What operating system did you use?
*MacOs*
### Do you have screenshots showing the problem?
<img width="366" alt="screen shot 2018-11-15 at 2 19 39 pm" src="https://user-images.githubusercontent.com/14067096/48585623-09d4e400-e8e2-11e8-835b-dea1a274a11d.png">

<img width="357" alt="screen shot 2018-11-15 at 2 20 28 pm" src="https://user-images.githubusercontent.com/14067096/48585627-0b9ea780-e8e2-11e8-95bf-26763f3f375a.png">

### What is your issue?
Token's balance displayed incorrectly if it's less than 1
Should be format '0.123' if balance is less than 1

**Comment by vbaranov** [comment]
@dennis00010011b is it still reproducible in 'develop' branch for you? I can't reproduce for now.

**Comment by dennis00010011b** [comment]
@vbaranov 
Yes, it is reproducible
Try account `ba98116a7d4b98f22f113c59448b9cc69f916d75f35d51f088b64b483fd0b8ca` 
There is DAI in mainnet , `0x06f0fe2c6be188b55049da39c9d7ca6ee9b6bf7c` in Ropsten
<img width="454" alt="screen shot 2018-11-23 at 8 01 34 am" src="https://user-images.githubusercontent.com/14067096/48952213-401fee00-eef6-11e8-8fee-7e65b5d8a1e0.png">
