### ISSUE TITLE
(Bug) Broken `eth_signTypedData_v3` method

### ISSUE THREAD

**Issue by rstormsf** [poanetwork/nifty-wallet#223]
If you are reporting a problem with Nifty Wallet, please include the following information:

### What browser and version did you use?
Chromium 71.0.3558.0
### What operating system did you use?
OSX
### Do you have screenshots showing the problem?
![image](https://user-images.githubusercontent.com/9360827/50001885-22f3b200-ffc0-11e8-8340-6e61f27194f7.png)

### What is your issue?
When calling `eth_signTypedData_v3` method, it doesn't pass arguments to the actual message to sign
while in new Metamask it works perfectly correct.

```js
const ethAccount = '0x123'
const domain = [
  { name: "name", type: "string" },
  { name: "version", type: "string" },
  { name: "chainId", type: "uint256" },
  { name: "verifyingContract", type: "address" },
  { name: "salt", type: "bytes32" },
];

const identity = [
  { name: "ethAddress", type: "address" }
];

const domainData = {
  name: "My App",
  version: "0.1",
  chainId: 3,
  verifyingContract: "0x1C56346CD2A2Bf3202F771f50d3D14a367B48070",
  salt: "0xf2d857f4a3edcb9b78b4d503bfe733db1e3f6cdc2b7971ee739626c97e86a558"
};
const message = {
  ethAddress: ethAccount
};

const data = {
  types: {
    EIP712Domain: domain,
    Identity: identity,
  },
  domain: domainData,
  primaryType: "Identity",
  message: message
};

const method = 'eth_signTypedData_v3'
const params = [ethAccount, data]

window.ethereum.sendAsync({
        method,
        params,
        from: ethAccount
      }, (err, {result}) => {
        
      })
```

**Comment by rstormsf** [comment]
Proof that the same message works fine in Metamask 
![image](https://user-images.githubusercontent.com/9360827/50002145-ebd1d080-ffc0-11e8-95d0-46de60a76f27.png)

**Comment by vbaranov** [comment]
@rstormsf I guess, the problem is how, you define `ethAccount`.

You can check, that `eth_signTypedData_v3` works perfect with Nifty Wallet with the JS Ethereum Signature Example page: https://danfinlay.github.io/js-eth-personal-sign-examples/ (at least, message params are passed).

**Comment by rstormsf** [comment]
![image](https://user-images.githubusercontent.com/9360827/50021064-b39ab400-fff9-11e8-8229-8c639459b107.png)
my same code works well even with old and new metamask...

**Comment by rstormsf** [comment]
@vbaranov 
By the way, https://danfinlay.github.io/js-eth-personal-sign-examples/ doesn't work with actual metamask.

I guess it's changed and you should update how nifty works
