### ISSUE TITLE
Add support for Firefox

### ISSUE THREAD

**Issue by filips123** [poanetwork/nifty-wallet#255]
Add support to download the addon from the Firefox Add-ons website.

**Comment by igorbarinov** [comment]
You can download builds of NiftyWallet for Firefox here https://github.com/poanetwork/nifty-wallet/releases

We don't plan to publish it in the Firefox Add-ons website at the moment.

**Comment by filips123** [comment]
Why you don't want to publish it?

**Comment by igorbarinov** [comment]
> Why you don't want to publish it?

Sorry about that. We don't have the operational capacity to publish it. Due to crypto winter, we rearranged priorities and teams. I hope that we will publish it in the future.

**Comment by filips123** [comment]
@igorbarinov Any update? Publishing to Firefox Add-ons website should not be hard.

**Comment by filips123** [comment]
@igorbarinov Ping.

**Comment by saturn-network** [comment]
@filips123 if you need a dapp wallet for Firefox and you plan to use $ETH or $ETC you can install [Saturn Wallet](https://www.saturn.network/blog/saturn-wallet/) today
