### ISSUE TITLE
Resolve issue with publishing in Chrome Store

### ISSUE THREAD

**Issue by igorbarinov** [poanetwork/nifty-wallet#274]
```
Dear Developer,

We have reviewed your item, "Nifty Wallet," with ID: jbdaocneiiinmjbjlgalhcelgbejmnid and it does not comply with our program policies. Please review this section of our policy:

Developers must not obfuscate code or conceal functionality of their extension. This also applies to any external code or resource fetched by the extension package.

Your item was found to have one or more files that does not comply with this policy.  An example of one such instance in your item is in contentscript.js.
``

**Comment by igorbarinov** [comment]
> Adding onto this - I cannot access the top Google result for Nifty Wallet
> 
> https://chrome.google.com/webstore/detail/nifty-wallet/jbdaocneiiinmjbjlgalhcelgbejmnid

Yes, because it was removed by Google from the Chrome store.
We are trying to bring it back.

**Comment by igorbarinov** [comment]
> As a fallback can you generate the packed extension from your CircleCI process so I can just download it without having to rebuild manually?

Yes, you can get the release from the GitHub https://github.com/poanetwork/nifty-wallet/releases

**Comment by vbaranov** [comment]
Nifty wallet was returned to [Google Chrome web store](https://chrome.google.com/webstore/detail/nifty-wallet/jbdaocneiiinmjbjlgalhcelgbejmnid?hl=ru)
