### ISSUE TITLE
Adding Custom Token doesnt work

### ISSUE THREAD

**Issue by SiddigZeidan** [poanetwork/nifty-wallet#296]
If you are reporting a problem with Nifty Wallet, please include the following information:

### What browser and version did you use?
Chrome
### Do you have screenshots showing the problem?
 
![image](https://user-images.githubusercontent.com/4807398/60147470-77f85800-979b-11e9-8b27-3d55fe447b4d.png)

### What is your issue?
Adding a custom token doesnt seem to work. I pasted the contract up above, but the fields below are still still inaccessible so I cant put in the name or the decimal places

**Comment by vbaranov** [comment]
@SiddigZeidan could you post the address of contract here? I don't see the full address from the screenshot

**Comment by vbaranov** [comment]
Published
