### ISSUE TITLE
RSK Mainet - Default gas price should match minimum gas price

### ISSUE THREAD

**Issue by fedejinich** [poanetwork/nifty-wallet#301]
Hi again!

We've been discussing with RSK team, and finally decided that default gas price should match minimum gas price.

In order to achive that, you can ask our node for minimum gas price, every time a user tries to send a transaction.

Important **minimum gas price must be consumed from the _best block_** (last block in the blockchain) 

Here is how you can get minimum gas price using curl

```bash 
> curl -X POST -H "Content-Type:application/json" --data '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":67}' https://public-node.rsk.co/
> {"jsonrpc":"2.0","id":67,"result":"0x16eb66"} // get best block number
> curl -X POST -H "Content-Type:application/json" --data '{ "jsonrpc": "2.0", "method": "eth_getBlockByNumber", "params": ["0x16eb66",true], "id": 67 }' https://public-node.rsk.co/
> { "jsonrpc": "2.0", "id": 67, "result": { "number": "0x16eb66", ..., "minimumGasPrice": "59240000" } }

```
There is an [RSKIP](https://github.com/rsksmart/RSKIPs/blob/master/IPs/RSKIP09.md) where you can find more information about minimium gas price.

Bests,

Fede

**Comment by vbaranov** [comment]
Hi @fedejinich. Is this correct, that for RSK testnet `minimumGasPrice` property is zero for all transactions? Does it mean that RSK testnet accepts 0-gas price transactions?

**Comment by fedejinich** [comment]
> Hi @fedejinich. Is this correct, that for RSK testnet `minimumGasPrice` property is zero for all transactions? Does it mean that RSK testnet accepts 0-gas price transactions?

actually in testnet gas price shouldn't be 0, in the ndoe there are some validations that prevents zero gas price tansactions. it should be the minium gas price posible (i.e. 1 gwei)

**Comment by vbaranov** [comment]
Published

**Comment by jonathansmirnoff** [comment]
@vbaranov thanks you for your help. We find another issue. The minimum gas price for mainnet is wrong. It should be 0.06 and it's smaller.

<img width="352" alt="Screen Shot 2019-07-05 at 11 09 31" src="https://user-images.githubusercontent.com/7558841/60729833-026a5580-9f1a-11e9-9b0a-8d6a591d93c6.png">

**Comment by vbaranov** [comment]
@jonathansmirnoff seems the screenshot is from the previous version of the extension. Could you force update an extension? It should be 4.11.8 version in the *info* section.

![Screenshot 2019-07-08 at 11 35 43](https://user-images.githubusercontent.com/4341812/60795605-9fc0c600-a174-11e9-844f-e61a4c2f104f.png)

![Screenshot 2019-07-08 at 11 35 56](https://user-images.githubusercontent.com/4341812/60795602-9fc0c600-a174-11e9-990a-d74221f69179.png)

**Comment by jonathansmirnoff** [comment]
@vbaranov thanks for your response. I reinstalled and checked the version of nifty, I have version 4.11.8 and I still have that issue.

**Comment by jonathansmirnoff** [comment]
@vbaranov we double checked it again and we found the issue. We think that it is set the gas price of testnet in mainnet network.

**Comment by vbaranov** [comment]
@jonathansmirnoff, it gets a gas price from the network you are connected to. I am not able to reproduce this issue. I still see what I posted in my screenshot. We get `minimumGasPrice` from the last block. And it equals every time to 0.05924 Gwei. Moreover, for the RSK testnet, this property is 0. That is why we return 1 gwei in case of RSK testnet. Could you guide me all the asteps to reproduce this problem?

**Comment by jonathansmirnoff** [comment]
@vbaranov yes sure.
1 -  Install Nifty Wallet (remove first)
2 - Connect to RSK Mainnet Network
3 - Try to transfer RBTC to an account
<img width="344" alt="Screen Shot 2019-07-12 at 17 06 04" src="https://user-images.githubusercontent.com/7558841/61155467-6915e300-a4c7-11e9-8f67-319e5cb755e7.png">
4 - Check that the GasPrice is `0,000003758` 
<img width="348" alt="Screen Shot 2019-07-12 at 17 02 44" src="https://user-images.githubusercontent.com/7558841/61155560-9a8eae80-a4c7-11e9-994b-837b16fa5a14.png">

**Comment by vbaranov** [comment]
@jonathansmirnoff, thanks for the details. I found the issue. Indeed, for some reasons it can get the gas price from blocks, which are from different chain you're connected to.
