### ISSUE TITLE
Add RIF Token to RSK network token lists

### ISSUE THREAD

**Issue by ilanolkies** [poanetwork/nifty-wallet#315]
Hi team!

Can we add RIF Token to RSK network token list by default?

Docs: https://developers.rsk.co/rif/
RSK MianNet: [0x2acc95758f8b5f583470ba265eb685a8f45fc9d5](https://explorer.rsk.co/address/0x2acc95758f8b5f583470ba265eb685a8f45fc9d5)
RSK TestNet: [0x19f64674d8a5b4e652319f5e239efd3bc969a1fe](https://explorer.testnet.rsk.co/address/0x19f64674d8a5b4e652319f5e239efd3bc969a1fe)

**Comment by vbaranov** [comment]
Hi @ilanolkies. If you could create and maintain a repository with tokens metadata for RSK like this one we have for POA tokens https://github.com/poanetwork/poa-contract-metadata we could easily integrate it into the wallet.

**Comment by ilanolkies** [comment]
Sure! Will ping you when ready :D

**Comment by vbaranov** [comment]
Actually these are ERC-721 https://github.com/poanetwork/poa-contract-metadata/blob/master/contract-map.json#L2-L14. You can just leave decimals as 0.

**Comment by ilanolkies** [comment]
Ok. I will add an NFT with `erc20: true`

**Comment by ilanolkies** [comment]
Are this ok?
https://github.com/rsksmart/rsk-contract-metadata
https://github.com/rsksmart/rsk-testnet-contract-metadata

**Comment by vbaranov** [comment]
@ilanolkies, yes, looks good 👍. Gonna add it to the next release.

**Comment by ilanolkies** [comment]
Thanks!

**Comment by vbaranov** [comment]
Released in `5.0.2`. Published in Google Chrome Web store.
