### ISSUE TITLE
Insufficient funds error

### ISSUE THREAD

**Issue by Emily7777** [poanetwork/nifty-wallet#357]
### What browser and version did you use?
Brave

### What operating system did you use?
Linux

### Do you have screenshots showing the problem?
I can't capture the error with a screenshot, as it goes away too fast.

### What is your issue?
I'm trying to send funds, I'm getting an "insufficient funds" error.  But there is plenty of POA to cover the transaction.

I was able to send 1 transaction from the wallet of 10POA.  The 2nd, and all others, fail.  In the Wallet, I get an error.  Required amount (the amount of the transaction), got "0".  But the POA shows in the wallet and in the blockchain.

Please advise.

**Comment by vbaranov** [comment]
@Emily7777 I wasn't managed to reproduce this behaviour. Try to re-login to the extension. Btw, is Nifty wallet updated in Brave to the latest version? The latest one currently is `5.0.1`. If no, try to update it forcefully.

**Comment by Emily7777** [comment]
Thanks.  It seems to be working now.
