### ISSUE TITLE
(Feature) New token icons for RSK

### ISSUE THREAD

**Issue by pmprete** [poanetwork/nifty-wallet#370]
RSK updated the tokens list and their icons:
- testnet: https://github.com/rsksmart/rsk-testnet-contract-metadata
- mainnet: https://github.com/rsksmart/rsk-contract-metadata

It would be nice to see the icons of those contracts on nifty wallet as well

**Comment by vbaranov** [comment]
Great, updated. Will be published in `5.0.3`
