### ISSUE TITLE
(Bug) Block explorer for ethereum is set to blockscout, which does not support ethereum. 

### ISSUE THREAD

**Issue by AJolly** [poanetwork/nifty-wallet#404]
The view on block explorer option connects to blockscout.  
This works fine for chains that blockscout supports, such as xDai, but fails when used to look up an ethereum account.  

"503 Service Unavailable
No server is available to handle this request."

We need to use a different block explorer for ethereum.

**Comment by tobutridaz** [comment]
+1

**Comment by vbaranov** [comment]
Thanks for noticing that. We were waiting for a long time publishing of 5.1.2 with the fix where Blockscout replaced with Etherscan for ETH Mainnet. Finally, It is published.
