### ISSUE TITLE
(UI Mistake) Copying token's smart contract address instead of wallet's address

### ISSUE THREAD

**Issue by Figazan** [poanetwork/nifty-wallet#410]
### What browser and version did you use?
*Microsoft Edge 84.0.522.58
### What operating system did you use?
Windows 10 Home Premium 64 bits
### Do you have screenshots showing the problem?
Yes, attached in issue
### What is your issue?
There's a critical UI bug where, if not being cautious, can make you copy a token's contract address instead of your wallet's.

If you click on the copy icon:

![20200904_195714](https://user-images.githubusercontent.com/70782459/92291717-4aa35000-eef0-11ea-834b-e78e2bdbe609.jpg)

or on the 3-dots menu, then the copy address option:

![20200904_195826](https://user-images.githubusercontent.com/70782459/92291735-5b53c600-eef0-11ea-8938-8c88ff504b71.jpg)

the user will have copied their wallet address successfully. 

However, if they go to the **token's 3-dot menu**, then the copy address option:

![20200904_195853](https://user-images.githubusercontent.com/70782459/92291780-8d652800-eef0-11ea-8a60-f70b37a92c33.jpg)

they will copy the token's smart contract address instead. This has already caused some users to accidentally burn their tokens when attempting to receive them in their wallets, unaware at that moment they just copied the token's contract address instead of their wallet's. 

This confusion is entirely avoidable with an updated UI that either moves this option to another part of the wallet less prone to mistakes of this kind, or hides it from this menu. Either way, it should explicitly state it is for copying the token's smart contract address.

**Comment by vbaranov** [comment]
Action name changed in 5.1.5
