### ISSUE TITLE
Send menu (RSK) complains about invalid checksum

### ISSUE THREAD

**Issue by shrlck81** [poanetwork/nifty-wallet#412]
If you are reporting a problem with Nifty Wallet, please include the following information:

### What browser and version did you use?
Chrome
### What operating system did you use?
Windows
### Do you have screenshots showing the problem?
![image](https://user-images.githubusercontent.com/71539404/93659104-2e3b0380-fa18-11ea-879f-97e13f8b4424.png)

### What is your issue?
Nifty complains that the destination address has an invalid checksum (RSK network).
But checking https://address-validator.rsk.co/ says that the address is ok

**Comment by vbaranov** [comment]
`0x6dCea26CEe6007666402Dc7F60079a71d94C0197` (which is on screenshot) is not a valid checksum based on https://github.com/rsksmart/RSKIPs/blob/master/IPs/RSKIP60.md. The valid one would be `0x6DceA26cee6007666402DC7F60079a71d94c0197`

![Screenshot 2020-10-20 at 15 31 47](https://user-images.githubusercontent.com/4341812/96586326-8308bd00-12e9-11eb-97fb-6c906400bb8f.png)
