### ISSUE TITLE
EIP-1193 - send is deprecated in favor of request

### ISSUE THREAD

**Issue by ilanolkies** [poanetwork/nifty-wallet#421]
If you are reporting a problem with Nifty Wallet, please include the following information:

### What browser and version did you use?

Google Chrome latest

### What operating system did you use?

MacOS

### Do you have screenshots showing the problem?

![Screen Shot 2020-11-12 at 19 19 02](https://user-images.githubusercontent.com/36084092/99003036-35fcbd00-251c-11eb-9ef6-5a4d3ee8cf58.png)

### What is your issue?

EIP-1193 specifies that Web3 providers should use `request` as function wrapper for RPCs. It also specifies that function `send` should be deprecated. This causes problems when handling both Metamask and Nifty support.

Refs:
- https://eips.ethereum.org/EIPS/eip-1193#request
- https://eips.ethereum.org/EIPS/eip-1193#send-deprecated

**Comment by vbaranov** [comment]
Included into 5.2.0. Published.
