### ISSUE TITLE
ERC-712 support

### ISSUE THREAD

**Issue by ilanolkies** [poanetwork/nifty-wallet#425]
### What browser and version did you use?

Chrome latest

### What operating system did you use?

Mac OS

### Do you have screenshots showing the problem?

![Screen Shot 2020-11-12 at 20 21 25](https://user-images.githubusercontent.com/36084092/99008433-ebcc0980-2524-11eb-9ac2-8f1669c8fae6.png)

### What is your issue?

Nifty does not support [ERC-712](https://eips.ethereum.org/EIPS/eip-712) (or at least not `v4`). This is a very important standard for user-facing applications. It moves the user one step forward on understanding what they are signing. Most Ethereum apps are now moving this way to improve user experience on security regards.

Expected behaviour (see domain data on the screen):

![Screen Shot 2020-11-12 at 20 22 40](https://user-images.githubusercontent.com/36084092/99008623-4b2a1980-2525-11eb-8e89-63c3f37044cd.png)

**Comment by vbaranov** [comment]
Included into 5.2.0. Published.
