### ISSUE TITLE
Infura v1 API is deprecated.  

### ISSUE THREAD

**Issue by AJolly** [poanetwork/nifty-wallet#439]
Nifty still uses infura's v1 API - which has been since deprecated.  

https://community.infura.io/t/notice-http-api-endpoint-deprecation/1851

We need to move the price lookup to an alternate, perhaps to coingecko instead?

**Comment by vbaranov** [comment]
Infura ETH Mainnet endpoint replaced with custom one in https://github.com/poanetwork/nifty-wallet/releases/tag/v5.2.3

**Comment by AJolly** [comment]
@vbaranov It has not been completely replaced, nifty is still unusable on eth atm.  

Check https://github.com/poanetwork/nifty-wallet/blob/master/app/scripts/controllers/infura.js

  async checkInfuraNetworkStatus () {
    const response = await fetch('https://api.infura.io/v1/status/metamask')
    const parsedResponse = await response.json()
    this.store.updateState({
      infuraNetworkStatus: parsedResponse,
    })
    return parsedResponse
  }

**Comment by vbaranov** [comment]
Infura status check removed from the bundle.
