### ISSUE TITLE
Unable to change derivation path for Ledge

### ISSUE THREAD

**Issue by creed-victor** [poanetwork/nifty-wallet#440]
If you are reporting a problem with Nifty Wallet, please include the following information:

### What browser and version did you use?
Google Chrome Version 87.0.4280.141 (Official Build) (x86_64)
### What operating system did you use?
Mac Os Big Sur 11.1
### Do you have screenshots showing the problem?
https://user-images.githubusercontent.com/69458664/104319157-26343180-54e9-11eb-838e-ec9776b7e6da.mov
### What is your issue?
I'm unable to connect ledger wallet to RSK network using "Ledger Live" derivation path, trying to change path instantly reselects "Ledgacy MEW/MYCrypto" path.

**Comment by vbaranov** [comment]
Ledger Live doesn't support RSK chain

<img width="491" alt="Screenshot 2021-02-03 at 12 09 40" src="https://user-images.githubusercontent.com/4341812/106723951-b7925180-6618-11eb-8b57-ad1219df1fee.png">
