### ISSUE TITLE
I'm receiving "duplicate error" after changing RPC/URL and trying to see my old address

### ISSUE THREAD

**Issue by jjmr007** [poanetwork/nifty-wallet#447]
If you are reporting a problem with Nifty Wallet, please include the following information:

### What browser and version did you use?
*Browser = Chrome (Version 88.0.4324.146 (Official Build) (64-bit)) / Nifty Wallet = Version 5.2.3*
### What operating system did you use?
*OS = Windows 10 (64-bit)*
### Do you have screenshots showing the problem?
*![NIFTY](https://user-images.githubusercontent.com/17028457/107391204-d7b98900-6ace-11eb-89ef-6a5c906e3d36.jpg)*
### What is your issue?
1. I exported my private key from the address i see in my default RSK profile
2. Created custom RPC w/ https://mainnet.sovryn.app/rpc
3. Went to "import account"
4. Selected "private key"
5. Pasted exported "private key"

Received duplicate error

**Comment by vbaranov** [comment]
@jjmr007 what did you expect? It looks for me like intended behaviour.

**Comment by jjmr007** [comment]
Hi, the intended behavior is to get visible the old address; with the new RPC/URL, that old address is no longer reachable for the wallet, or is hidden. Thanks

**Comment by jjmr007** [comment]
Thank u very much!

**Comment by vbaranov** [comment]
Nifty Wallet 5.2.4 with the fix published.
