### ISSUE TITLE
Rsk chain. It Is not possibile to export the account and other problems

### ISSUE THREAD

**Issue by fabr784** [poanetwork/nifty-wallet#449]
Brave 1.20.103 Chromium 88.0.4324.152 Build ufficiale 64 bit
Windows 10
Problems on RSK chain:
1) It Is not possible to export the account
2) the account unexpectedly changes between Rsk to Eth address when you close e reopen wallet
3) the account and custom token disappear when you close and reopen wallet
![Screenshot_2021-02-14-22-36-40-322_org telegram messenger](https://user-images.githubusercontent.com/79062578/107891916-e0242080-6f21-11eb-8c7d-4cf97a617d6e.jpg)

**Comment by Digital-Alchemist1** [comment]
Having exact same issue. 
1. Exporting the RSK account gives error while password is correct.
2. At same time, the wallet address changes and when changed back to RSK address, tokens have disappeared.

![image](https://user-images.githubusercontent.com/78158254/108193518-d19e5a80-7115-11eb-9a71-a4545fa93324.png)

**Comment by fabr784** [comment]
@vbaranov About point 3. Do these steps: open wallet, go to Rsk chain, edit account and add token. Close wallet. Reopen wallet. On the top you can see Rsk chain but really you are on Eth chain (check account address). Go to Rsk chain e you can see that no account Is edited and no token Is added.

**Comment by vbaranov** [comment]
Let's keep one ticket per problem.
1. is resolved with recently published Nifty Wallet 5.2.4.
For 2. we have https://github.com/poanetwork/nifty-wallet/issues/423 https://github.com/poanetwork/nifty-wallet/issues/265.
For 3. - https://github.com/poanetwork/nifty-wallet/issues/445
