### ISSUE TITLE
Create a property web3.currentProvider.isNifty

### ISSUE THREAD

**Issue by clbrge** [poanetwork/nifty-wallet#64]
*  Expected Behavior
web3.currentProvider.isNifty is true 

  *  Actual Behavior
only web3.currentProvider.isMetaMask is defined. Of course that behavior should be kept for backwards compatibility with Dapp develop for MetaMask.

**Comment by 6proof** [comment]
Looks like this would solve https://github.com/poanetwork/metamask-extension/issues/47 - allow Nifty Wallet  and MetaMask to peacefully coexist.  Also allows DApp developers to  deliver unique features when NiftyWallet is detected.
